### ISSUE TITLE
任务是动态添加的还是静态添加的呢？

### ISSUE THREAD

**Issue by azataiot** [MorvanZhou/whenact#1]
刚看到，很有用处的一个项目，我只是想这里的任务是动态添加的就好了，类似于daemon 的形式。

**Comment by MorvanZhou** [comment]
请问你指的是在 pipeline 构建好之后，在pipeline.run() 的时候，中途添加 when 或者 act 模块吗？

**Comment by azataiot** [comment]
> 请问你指的是在 pipeline 构建好之后，在pipeline.run() 的时候，中途添加 when 或者 act 模块吗？

是的，运行后是否有办法添加新的任务呢？之前就一直想写一个类似的东西，今天看到你已经开始写了。

**Comment by MorvanZhou** [comment]
我确认一下，这个库，我是写来做策略执行的，when 是一种条件（不是时间），action 是条件满足后的执行策略。有点像控制智能体的一种策略方式。不知道你理解的是否是这样，又或者这个库也能兼容你其他的想法。如果可以在不改变库属性的大前提下兼容你的逻辑，我觉得也是可以加进库的。
这个库不是在模拟一个 scheduler，如果是 scheduler 这样的功能，python 应该有其他库可以满足需求。

**Comment by azataiot** [comment]
是的， 理解是正确的。我在想如何加入一些功能，如果成功实现，我会PR。

**Comment by MorvanZhou** [comment]
感谢一同构建。因为这个库还处在前期快速迭代时刻。所以变动会频繁一些，还请留意conflict
